"""added birth date

Revision ID: 8d3443fcdd1d
Revises: d18903d5daa5
Create Date: 2026-06-14 23:44:52.942925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d3443fcdd1d'
down_revision: Union[str, Sequence[str], None] = 'd18903d5daa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'birth_date')
    # ### end Alembic commands ###
